### ISSUE TITLE
Error ketika activate theme

### ISSUE THREAD

**Issue by xprbs** [mastekno-com/mediumku-mastekno#1]
```Parse error: syntax error, unexpected 'else' (T_ELSE), expecting end of file in /var/www/html/wordpress/wp-content/themes/mediumku-mastekno-master/inc/custom.php on line 82```

![image](https://user-images.githubusercontent.com/63851808/79695996-3396f500-82a4-11ea-9ebe-4c6d9d88da28.png)

**Comment by intprism** [comment]
line 82 coba diganti dengan
<?php
if (is_home() && !is_paged()) {
    echo "\x3cp\x20c\x6ca\x73\x73\x3d\x22p\x75\x6c\x6c-\x72\x69\x67h\x74\x22\x20t\x69t\x6ce\x3d\x22T\x65\x6dp\x6ca\x74e\x20\x42\x79:\x20\x4da\x73T\x65k\x6e\x6f\x2e\x63o\x6d\x22>\x54\x65m\x70\x6ca\x74\x65 \x42y\x3a \x4d\x61\x73T\x65\x6b\x6eo\x2e\x63\x6fm\x3c/\x70>";
}else {
    echo "\x3cp\x20c\x6ca\x73\x73\x3d\x22p\x75\x6c\x6c-\x72\x69\x67h\x74\x22\x20t\x69t\x6ce\x3d\x22T\x65\x6dp\x6ca\x74e\x20\x42\x79:\x20\x4da\x73T\x65k\x6e\x6f\x2e\x63o\x6d\x22>\x54\x65m\x70\x6ca\x74\x65 \x42y\x3a \x4d\x61\x73T\x65\x6b\x6eo\x2e\x63\x6fm\x3c/\x70>";
}
?>

**Comment by mastekno-com** [comment]
sudah di perbaiki ya
