### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by aurielly** [mastekno-com/mediumku-mastekno#2]
Gimana cara edit menunya? di sidebar bagian appearance ga ada "menu" saya rubah lwat customize juga ga berubah sama sekali

**Comment by IDaldi** [comment]
sama menu tidak berfungsi mas tekno...

**Comment by IhwanID** [comment]
untuk sementara bisa di hardcode dulu menu nya. 
Appareance -> Theme Editor -> Edit Theme Header (header.php)
